
version: 2

models:
    - name: customer_base
      description: "Initial cleaning of customer table"
      columns:
          - name: customer_customerid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: customer_email
      description: "Unique customer + email combinations"
      columns:
          - name: pk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: customer_phone
      description: "Unique customer + phone combinations"
      columns:
          - name: pk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: customer_sfcc_id
      description: "Unique customer + sfcc ID"
      columns:
          - name: pk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: recipient
      description: "Unique recipient email + phone combinations"
      columns:
          - name: pk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
