
version: 2

models:
    - name: lineitem_base
      description: "Initial cleaning of lineitem table"
      columns:
          - name: pk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: lineitem_filtered
      description: "Filtering lineitem_base"
      columns:
          - name: pk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

